sudo: required

git:
  depth: 3

services:
  - docker

install:
  - docker build --tag guillaume-florent/aocutils:latest .

script:
  - docker run --name aocutils guillaume-florent/aocutils:latest /bin/bash -c "cd /opt/aoc-utils;pytest tests/"

after_script:
  - docker images
