package:
  name: aocutils
  version: "18.2.0"

source:
  path: ../aoc-utils

build:
  number: 1
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  include_recipe: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - corelib
    - numpy
    - scipy
    # - OCC
    - wxpython
    - pyqt

#test:
#  requires:
#    - pytest
#  source_files:
#    - tests
#  commands:
#    - pytest tests/

about:
  home: https://github.com/guillaume-florent/aoc-utils
  license: GPLv3
  license_file: LICENSE.txt
  summary: PythonOCC wrapper and utilities
